### PR TITLE
Set up for inclusion as an Arduino library.

### PR DESCRIPTION
**Pull request by bendory**
Documentation is available [here](https://arduino.github.io/arduino-cli/0.28/library-specification/).

This PR will work for submission as-is, but it turns out there are two issues that make it a little uglier than desired:

1) I've re-arranged everything to comply with the Library layout, and that means that I've broken
all existing deep links into your Github repo. That's not friendly.

2) I've included everything in your original repo under the `/extras/` directory, but most of this is
not needed for the Arduino library, and it makes the download unnecessarily large.

IMO, a cleaner way to prepare the Arduino Library submission would be to:

1) Fork your repo into a new `botletics/SIM7000-Shield-Library` (or you pick some other name).
2) Delete all the non-code from there -- this is likely the entire `/extras/` subdir.
3) Migrate code to the `/src/` directory as I have done.
4) Update `botletics/SIM7000-LTE-Shield` to delete the `/Code/` directory; in its place, add a `README` that sends users to the new Library.

So this is your choice here as the Botletics owner -- you can accept this PR as is and I'll follow it with a PR for [submission](https://github.com/arduino/library-registry/blob/main/FAQ.md#submission) _OR_ set up a fork (or even a completely empty repo) called `botletics/SIM7000-Shield-Library` (or feel free to pick some other name that you like) and I'll do the rest of the work to prepare the submission to Arduino.

(There is a third option -- I can just fork your repo and prepare the Library submission completely independently from you, but I have to be honest and admit that I'm unlikely to keep my fork in sync with your ongoing development of the source code.)

LMK how I can help!

### CODE REVIEW

**Comment by botletics** [comment]
Thank you so much, I really appreciate it! I'll aim for the cleaner option, but I'm not the most GitHub savvy, so I'll see what I can do.

**Comment by botletics** [comment]
OK, so I created a new repo with GitHub Desktop. I rearranged the files according to how you described with `/src/` and `/extras/`. I pushed it to Github.com but I think it's taking time for those files to actually show up... hope I did it right lol.

**Comment by botletics** [comment]
Also, how should I handle version releases on the new repo?

**Comment by bendory** [comment]
> * Would it be better to delete the `/extras/` directory in the new repo and just manage that here in this repo (along with the wiki), so I don't have copies in 2 different places?

Yes, I would do exactly that. Specifically:

- completely delete this entire directory: https://github.com/botletics/SIM7000-Shield-Library/tree/main/extras
- I'm not sure why you have https://github.com/botletics/SIM7000-Shield-Library/blob/main/src/.travis.yml over there, presumably you're using a Travis build somewhere? The file isn't needed for the Arduino library, but it's harmless, so you can leave it if you want -- or delete it to prevent confusion.
- Fix the URL is https://github.com/botletics/SIM7000-Shield-Library/blob/main/src/library.properties to point to https://github.com/botletics/SIM7000-Shield-Library
- Delete the contents of the entire [Code directory](https://github.com/botletics/SIM7000-LTE-Shield/tree/master/Code) and add a `README.md` pointing people to https://github.com/botletics/SIM7000-Shield-Library for source code.

Once you've got the above, ping me and I'll make the Arduino submission.

**Comment by bendory** [comment]
Actually, all that's needed to move forward with the Library submission is in [this PR](https://github.com/botletics/SIM7000-Shield-Library/pull/1); if you accept that PR, then my [above comments](https://github.com/botletics/SIM7000-LTE-Shield/pull/314#issuecomment-1297091567) are reduced to:

- I'm not sure why you have https://github.com/botletics/SIM7000-Shield-Library/blob/main/src/.travis.yml over there, presumably you're using a Travis build somewhere? The file isn't needed for the Arduino library, but it's harmless, so you can leave it if you want -- or delete it to prevent confusion.
- Delete the contents of the entire [Code directory](https://github.com/botletics/SIM7000-LTE-Shield/tree/master/Code) and add a `README.md` pointing people to https://github.com/botletics/SIM7000-Shield-Library for source code.

But neither of these are blockers for the library submission -- once the PR is accepted, I can go ahead and submit.

**Comment by botletics** [comment]
Thanks! I merged the PR on the new repo!

**Comment by botletics** [comment]
What about versioning/releases though? When I create new releases, will it show up in Arduino IDE?

**Comment by bendory** [comment]
I think you're going to do releases by setting up tags in the new repo -- will send you details once I figure it all out.

**Pull request closed without merging**
