### PR TITLE
MQTTS using TCP

### PR DESCRIPTION
**Pull request by ikstvn**
Hi Timothy,

Hope you're doing good with Botletics. I recently developed the TLS feature for MQTT using TCP and want to contribute with it. At the end of the README is the description of what I've done and the configuration I used to add SSL support. I hope you find it useful. Any questions about it, just let me know :)

Best regards,
Kevin

### CODE REVIEW

**Comment by botletics** [comment]
Thanks a ton for doing this! Do you by any chance have an example sketch that shows the full process, as well as serial monitor logs? It all looks logical but I'm thinking of how I would change the example sketches to include this.

**Comment by cmendes0101** [comment]
I'm interested in checking this out but I'm not totally sure how to use it correctly. Would you have an example sketch?

**Review by botletics — APPROVED** [review]
Sorry for the delay, but thank you for working on this!

**Comment by botletics** [comment]
I've updated the library to add these features, with some slight mods. Thanks for your work!

**Pull request closed without merging**
